name: Alerta
on:
  schedule:
    - cron: '35 13,18,23 * * *' # 10h, 15h, 20h BRT
  workflow_dispatch:

permissions:
  contents: write  # <--- PERMISSÃO CRÍTICA PARA SALVAR O JSON

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install axios

      - name: Executar Monitor
        env:
          GOLD_API_KEY: ${{ secrets.GOLD_API_KEY }}
          PUSH_USER: ${{ secrets.PUSH_USER }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: node monitor.js

      # Passo extra: Salvar o arquivo dados.json atualizado no repositório
      - name: Commit e Push das alterações
        run: |
          git config --global user.name "Bot Monitor"
          git config --global user.email "bot@github.com"
          git add dados.json
          # Só faz commit se houver mudança
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualizando dados históricos [skip ci]" && git push)
